name: Deploy

on:
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Print environment
        run: |
          echo "Running in environment: test"
